### ISSUE TITLE
Duplicate key - exception when generating new term-id

### ISSUE THREAD

**Issue by jormigo** [jormigo/mlsa#2]
```
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable1 source, Func2 predicate)
   at Common.TermDictionary.get_Item(UInt64 i) in C:\Users\jrami\Documents\mlsa\SAEngine\Common\TermDictionary.cs:line 34
   at DocumentCollections.DocumentCollection.ProcessDocuments(List1 documents) in C:\Users\jrami\Documents\mlsa\SAEngine\DocumentCollectionManager\DocumentCollection.cs:line 183
   at DocumentCollections.DocumentCollection.ProcessDocument(IDocument doc) in C:\Users\jrami\Documents\mlsa\SAEngine\DocumentCollectionManager\DocumentCollection.cs:line 173
   at DocumentCollections.DocumentCollection.Add(IDocument document) in C:\Users\jrami\Documents\mlsa\SAEngine\DocumentCollectionManager\DocumentCollection.cs:line 220
   at MLSACore.Lex.OnNext(IList1 documents) in C:\Users\jrami\Documents\mlsa\SAEngine\MLSACore\Lex.cs:line 121
   at DataSourceEngine.Rss.RssDocumentProvider.ReportLatestDocuments() in C:\Users\jrami\Documents\mlsa\SAEngine\DataSourceEngine\Rss\RssDocumentProvider.cs:line 63
   at DataSourceEngine.Rss.RssDocumentProvider.Work(CancellationToken token) in C:\Users\jrami\Documents\mlsa\SAEngine\DataSourceEngine\Rss\RssDocumentProvider.cs:line 104
   at DataSourceEngine.DocumentProvider.<>c__DisplayClass23_0.<Run>b__0() in C:\Users\jrami\Documents\mlsa\SAEngine\DataSourceEngine\DocumentProvider.cs:line 83
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by jormigo** [comment]
Resolved:
Commit: d0f2b87dfea16eac8fe789c399c0ce2c1ff96807 [d0f2b87]
Parents: cf745d55a0
Author: Jorge M Ramirez <compiled.in.california@gmail.com>
Date: Tuesday, August 16, 2016 10:56:47 AM
